import type { GlossaryTerm } from "./types";

export const glossaryTerms: GlossaryTerm[] = [
  {
    id: "algorithm",
    ru: "алгоритм",
    en: "algorithm",
    kk: "алгоритм",
    definition: "Точный способ решить задачу: какие действия выполнить и в каком порядке.",
    example: "Сортировка массива, поиск минимума и обход графа - это алгоритмы.",
    related: ["complexity", "implementation"],
  },
  {
    id: "complexity",
    ru: "сложность",
    en: "complexity",
    kk: "күрделілік",
    definition: "Оценка того, как растет время работы или память программы при увеличении входных данных.",
    example: "O(n) обычно означает один проход по массиву из n элементов.",
    related: ["big-o", "time-limit"],
  },
  {
    id: "big-o",
    ru: "O-нотация",
    en: "Big O notation",
    definition: "Краткая запись верхней оценки роста времени или памяти алгоритма.",
    example: "O(n log n) часто встречается у эффективных сортировок.",
    related: ["complexity"],
  },
  {
    id: "input",
    ru: "ввод",
    en: "input",
    kk: "енгізу",
    definition: "Данные, которые программа получает от проверяющей системы.",
    example: "В задачах формат ввода обычно описан отдельным разделом.",
    related: ["output", "stdin"],
  },
  {
    id: "output",
    ru: "вывод",
    en: "output",
    kk: "шығару",
    definition: "Ответ, который программа печатает для проверяющей системы.",
    example: "Лишний пробел редко опасен, но лишняя строка может дать Wrong Answer.",
    related: ["input", "stdout"],
  },
  {
    id: "stdin",
    ru: "стандартный ввод",
    en: "standard input",
    definition: "Обычный поток, из которого программа читает данные на соревнованиях.",
    example: "В C++ обычно используют cin, в Python - input().",
    related: ["input"],
  },
  {
    id: "stdout",
    ru: "стандартный вывод",
    en: "standard output",
    definition: "Обычный поток, куда программа печатает ответ.",
    example: "В C++ используют cout, в Python - print().",
    related: ["output"],
  },
  {
    id: "simulation",
    ru: "симуляция",
    en: "simulation",
    definition: "Решение, которое прямо моделирует процесс из условия задачи.",
    example: "Если корова поворачивает каждую минуту, можно пошагово хранить ее координаты.",
    related: ["implementation"],
  },
  {
    id: "implementation",
    ru: "реализация",
    en: "implementation",
    definition: "Перевод идеи решения в корректную программу.",
    example: "Идея может быть правильной, но ошибка в индексах ломает реализацию.",
    related: ["algorithm", "debugging"],
  },
  {
    id: "array",
    ru: "массив",
    en: "array",
    kk: "массив",
    definition: "Структура данных, где элементы идут подряд и доступны по индексу.",
    example: "Массив оценок учеников можно пройти циклом и найти максимум.",
    related: ["index", "loop"],
  },
  {
    id: "index",
    ru: "индекс",
    en: "index",
    definition: "Номер позиции элемента в массиве или строке.",
    example: "Во многих языках первый элемент имеет индекс 0.",
    related: ["array", "off-by-one"],
  },
  {
    id: "loop",
    ru: "цикл",
    en: "loop",
    kk: "цикл",
    definition: "Конструкция, которая повторяет действия несколько раз.",
    example: "Цикл for удобно использовать для прохода по массиву.",
    related: ["array"],
  },
  {
    id: "off-by-one",
    ru: "ошибка на единицу",
    en: "off-by-one error",
    definition: "Типичная ошибка, когда цикл делает на один шаг больше или меньше нужного.",
    example: "Идти до i <= n вместо i < n часто приводит к выходу за границы массива.",
    related: ["index", "debugging"],
  },
  {
    id: "edge-case",
    ru: "крайний случай",
    en: "edge case",
    definition: "Редкий или минимальный/максимальный вход, на котором легко ошибиться.",
    example: "n = 1, пустой ответ или все элементы одинаковые - частые крайние случаи.",
    related: ["debugging"],
  },
  {
    id: "time-limit",
    ru: "лимит времени",
    en: "time limit",
    kk: "уақыт шектеуі",
    definition: "Максимальное время, за которое программа должна завершиться на тесте.",
    example: "Если n = 200000, решение O(n^2) почти наверняка не пройдет.",
    related: ["complexity"],
  },
  {
    id: "memory-limit",
    ru: "лимит памяти",
    en: "memory limit",
    definition: "Максимальный объем памяти, доступный программе.",
    example: "Матрица 100000 x 100000 не поместится в обычный лимит памяти.",
    related: ["complexity"],
  },
  {
    id: "greedy",
    ru: "жадный алгоритм",
    en: "greedy algorithm",
    definition: "Подход, где на каждом шаге выбирается локально лучший вариант.",
    example: "Сортировать события и брать первое подходящее - частый жадный шаблон.",
    related: ["algorithm"],
  },
  {
    id: "sorting",
    ru: "сортировка",
    en: "sorting",
    kk: "сұрыптау",
    definition: "Упорядочивание элементов по возрастанию, убыванию или другому правилу.",
    example: "После сортировки легче искать соседние элементы с минимальной разницей.",
    related: ["array", "complexity"],
  },
  {
    id: "prefix-sum",
    ru: "префиксные суммы",
    en: "prefix sums",
    definition: "Массив накопленных сумм, который помогает быстро считать сумму на отрезке.",
    example: "sum(l, r) можно получить за O(1), если заранее посчитать префиксы.",
    related: ["array"],
  },
  {
    id: "two-pointers",
    ru: "два указателя",
    en: "two pointers",
    definition: "Техника, где две позиции двигаются по массиву или строке по определенному правилу.",
    example: "Два указателя часто применяют после сортировки.",
    related: ["array", "sorting"],
  },
  {
    id: "graph",
    ru: "граф",
    en: "graph",
    kk: "граф",
    definition: "Модель из вершин и ребер, описывающая связи между объектами.",
    example: "Города и дороги между ними можно представить графом.",
    related: ["dfs", "bfs"],
  },
  {
    id: "dfs",
    ru: "поиск в глубину",
    en: "depth-first search",
    definition: "Алгоритм обхода графа, который уходит глубже по ребрам, пока это возможно.",
    example: "DFS удобно использовать для поиска компонент связности.",
    related: ["graph", "bfs"],
  },
  {
    id: "bfs",
    ru: "поиск в ширину",
    en: "breadth-first search",
    definition: "Алгоритм обхода графа слоями от стартовой вершины.",
    example: "BFS на невзвешенном графе находит кратчайшее число ребер.",
    related: ["graph", "dfs"],
  },
  {
    id: "dynamic-programming",
    ru: "динамическое программирование",
    en: "dynamic programming",
    definition: "Подход, где задача разбивается на состояния, а ответы для состояний переиспользуются.",
    example: "Классический пример - число способов дойти до клетки в таблице.",
    related: ["state"],
  },
  {
    id: "state",
    ru: "состояние",
    en: "state",
    definition: "Набор параметров, который достаточно знать для подзадачи.",
    example: "В DP по рюкзаку состояние может быть позицией и текущим весом.",
    related: ["dynamic-programming"],
  },
  {
    id: "test-case",
    ru: "тест",
    en: "test case",
    kk: "тест",
    definition: "Один вход и ожидаемый ответ, на котором проверяется программа.",
    example: "Перед отправкой полезно придумать свои маленькие тесты.",
    related: ["debugging"],
  },
  {
    id: "debugging",
    ru: "отладка",
    en: "debugging",
    definition: "Поиск и исправление ошибки в программе или идее решения.",
    example: "Печатать промежуточные значения полезно, но перед отправкой их нужно убрать.",
    related: ["edge-case", "test-case"],
  },
  {
    id: "accepted",
    ru: "Accepted",
    en: "Accepted",
    definition: "Вердикт, означающий, что программа прошла все тесты проверяющей системы.",
    example: "Accepted не доказывает идеальность решения, но означает, что оно прошло данный набор тестов.",
    related: ["wrong-answer", "time-limit"],
  },
  {
    id: "wrong-answer",
    ru: "Wrong Answer",
    en: "Wrong Answer",
    definition: "Вердикт, означающий неправильный ответ хотя бы на одном тесте.",
    example: "Причиной может быть неверная идея, ошибка реализации или неучтенный крайний случай.",
    related: ["debugging", "edge-case"],
  },
  {
    id: "interactive-problem",
    ru: "интерактивная задача",
    en: "interactive problem",
    definition: "Задача, где программа общается с проверяющей системой во время работы.",
    example: "Интерактивные задачи чаще встречаются на продвинутых этапах.",
    related: ["output"],
  },
];

export function getGlossaryTerm(id: string) {
  return glossaryTerms.find((term) => term.id === id);
}
